---
  ##############################
  # IE processing parameters
  ##############################
  # directory for original text
  txt_dir: /home/daviden1013/David_projects/NLP_IE_Pipelines/data/text
  # directory for annotated files
  ann_dir: /home/daviden1013/David_projects/NLP_IE_Pipelines/data/ann
  # directory for IE files
  IE_dir:  /home/daviden1013/David_projects/NLP_IE_Pipelines/IE
